/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mx.carmona.principal;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.bind.JAXBException;

/**
 *
 * @author Edwin Carmona
 */
public class ReaderWindow extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form SFormRate
     */
    public ReaderWindow() {
        initComponents();
        custom();
    }
    
    private void custom() {
        jbOpen.addActionListener(this);
        jbProcess.addActionListener(this);
    }
    
    private void seleccionarArchivos() {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivo .xml", "xml");
        chooser.setFileFilter(filter);
        chooser.setMultiSelectionEnabled(true);
        chooser.showOpenDialog(this);
        
        File[] files = chooser.getSelectedFiles();
        
        jtArea.setText("");
        for (File file: files) {
            jtArea.setText(file.getName() + "\n" + jtArea.getText());
        }
        if(files.length >= 2) {
            
        }
        
        Utils u = new Utils();
        
        try {
            u.procesarXmls(files);
        }
        catch (JAXBException ex) {
            Logger.getLogger(ReaderWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void process() {
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbOpen = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jbProcess = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lector de XML"));
        jPanel1.setLayout(new java.awt.GridLayout(3, 2));

        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("Seleccionar archivos:");
        jPanel2.add(jLabel1);

        jbOpen.setText("Abrir");
        jPanel2.add(jbOpen);
        jPanel2.add(jLabel3);
        jPanel2.add(jLabel4);

        jLabel5.setText("Archivos seleccionados:");
        jPanel2.add(jLabel5);
        jPanel2.add(jLabel6);

        jPanel1.add(jPanel2);

        jtArea.setColumns(20);
        jtArea.setRows(5);
        jScrollPane1.setViewportView(jtArea);

        jPanel1.add(jScrollPane1);

        jPanel4.setLayout(new java.awt.GridLayout(3, 2));
        jPanel4.add(jLabel7);
        jPanel4.add(jLabel8);
        jPanel4.add(jLabel9);

        jbProcess.setText("Procesar");
        jPanel4.add(jbProcess);
        jPanel4.add(jLabel11);
        jPanel4.add(jLabel12);

        jPanel1.add(jPanel4);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbOpen;
    private javax.swing.JButton jbProcess;
    private javax.swing.JTextArea jtArea;
    // End of variables declaration//GEN-END:variables


    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof javax.swing.JButton) {
            javax.swing.JButton button = (javax.swing.JButton) e.getSource();

            if (button == jbOpen) {
                seleccionarArchivos();
            }
            else if (button == jbProcess) {
                process();
            }
        }
    }

}
